import { Button } from "@/components/ui/button";
import Link from "next/link";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auth - Cartzeno",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="absolute top-0 left-0 right-0 p-4 w-fit bg-white">
        <Button asChild variant={"outline"}>
          <Link href="/">Home</Link>
        </Button>
      </div>
      <div className="font-poppins">{children}</div>
    </>
  );
}
