import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home - Cartzeno",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (typeof window != "undefined") {
    return (
      <>
        <div className="font-poppins">{children}</div>
      </>
    );
  }
}
